# Generated by Django 3.2.6 on 2021-08-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizontalSpatialCoordinate', models.IntegerField()),
                ('verticalSpatialCoordinate', models.IntegerField()),
                ('ffmcIndex', models.FloatField()),
                ('dmcIndex', models.FloatField()),
                ('dcIndex', models.FloatField()),
                ('isi', models.FloatField()),
                ('temperature', models.FloatField()),
                ('relativeHumidity', models.FloatField()),
                ('wind', models.FloatField()),
                ('rain', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('modelInput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.modelinput')),
            ],
        ),
    ]
