# Generated by Django 3.2.6 on 2021-08-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_modeloutput_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloutput',
            name='area',
            field=models.FloatField(),
        ),
    ]
